In [1]:
#!pip install pandas

In [2]:
import pandas as pd

df = pd.DataFrame({
    'temperature': [10, 7, 4, 0],
    'sales'      : [30, 50, 60, 80]
})

display(df)

,temperature,sales
0,10,30
1,7,50
2,4,60
3,0,80


In [3]:
#   입력 값
#df['temperature'].values  #     1차원 배열로 출력
#df[['temperature']].values#     2차원 배열로 출력(정수형)
X = df[['temperature']].values.astype('float32')

X

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [4]:
#   실제 값
y = df[['sales']].values.astype('float32')

y

array([[30.],
       [50.],
       [60.],
       [80.]], dtype=float32)

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [6]:
X

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [7]:
y

array([[30.],
       [50.],
       [60.],
       [80.]], dtype=float32)

In [8]:
"""
tensorflow Dense(): 선형 회귀를 계산
    layer.Dense(#, ): 진짜 값(y)의 칸 수(#칸)
    input_shape = (#, ): 입력값(x)의 칸, 줄 수(줄은 생략 가능)[X: #칸 _줄]
"""

model = keras.Sequential([
    layers.Dense(1, input_shape = (1, ))
])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(
    optimizer = keras.optimizers.SGD(learning_rate = 0.001),
    loss = 'mse'
)

In [11]:
history = model.fit(X, y, epochs = 10000, verbose = 0)

In [ ]:
#history.history['loss']#    cost 변화치 확인
history.history['loss'][-1]

4.342370986938477

In [22]:
weight, bias = model.layers[0].get_weights()

a_value = weight[0][0]
b_value = bias[0]

print(f'weight = {weight[0][0]}')
print(f'bias = {bias[0]}')
#print(f'weight = {weight}')#    2차원 배열
#print(f'bias = {bias}')    #    1차원 배열

weight = -4.8253045082092285
bias = 80.29499053955078


In [23]:
X

array([[10.],
       [ 7.],
       [ 4.],
       [ 0.]], dtype=float32)

In [24]:
X * a_value + b_value

array([[32.041946],
       [46.51786 ],
       [60.993774],
       [80.29499 ]], dtype=float32)

In [ ]:
pred_y = model.predict(X)

1/1 [==============================] - 0s 16ms/step


array([[32.041946],
       [46.51786 ],
       [60.993774],
       [80.29499 ]], dtype=float32)

In [29]:
np.array([[5]], dtype = 'float32') * a_value + b_value

array([[56.16847]], dtype=float32)

In [30]:
model.predict(np.array([[5]], dtype='float32'))

1/1 [==============================] - 0s 650us/step


array([[56.16847]], dtype=float32)