In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'temperature': [10, 7, 4, 0],
    'sales':       [30, 50, 60, 80]
})

display(df)

,temperature,sales
0,10,30
1,7,50
2,4,60
3,0,80


In [3]:
df['temperature']

0    10
1     7
2     4
3     0
Name: temperature, dtype: int64

In [4]:
df['temperature'].values

array([10,  7,  4,  0])

In [5]:
import torch
x_tensor = torch.tensor(df['temperature'].values, dtype = torch.float32)

x_tensor

tensor([10.,  7.,  4.,  0.])

In [6]:
y_tensor = torch.tensor(df['sales'].values, dtype = torch.float32)

y_tensor

tensor([30., 50., 60., 80.])

In [7]:
a = torch.tensor(-4.0, requires_grad = True)

a

tensor(-4., requires_grad=True)

In [8]:
b = torch.tensor(80.0, requires_grad = True)

b

tensor(80., requires_grad=True)

In [9]:
learning_rate = 0.001
epochs = 1000
cost_history = []

In [10]:
a_initial = a.item()

a_initial

-4.0

In [11]:
b_initial = b.item()

b_initial

80.0

In [12]:
with torch.no_grad():
    #   진짜값 - 예측값
    error = (y_tensor - (x_tensor * a + b))
    print(f'error = {error}')
    
    initial_cost = torch.mean(error ** 2).item()
    print(f'initial_cost = {initial_cost}')

error = tensor([-10.,  -2.,  -4.,   0.])
initial_cost = 30.0


In [13]:
for epoch in range(epochs):
    pred = a * x_tensor + b
    
    error = y_tensor - pred
    
    cost = torch.mean(error ** 2)
    cost.backward()
    
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        
    a.grad.zero_()
    b.grad.zero_()
    
    cost_history.append(cost.item())
    
    if epoch % 100 == 0:
        print(f'epoch = {epoch}, Cost = {cost}, a = {a}, b = {b}')

epoch = 0, Cost = 30.0, a = -4.065000057220459, b = 79.99199676513672
epoch = 100, Cost = 4.413737773895264, a = -4.778783798217773, b = 79.93325805664062
epoch = 200, Cost = 4.4044413566589355, a = -4.782774448394775, b = 79.96345520019531
epoch = 300, Cost = 4.39629602432251, a = -4.786402702331543, b = 79.99173736572266
epoch = 400, Cost = 4.389142036437988, a = -4.789800643920898, b = 80.01825714111328
epoch = 500, Cost = 4.38286828994751, a = -4.7929863929748535, b = 80.04309844970703
epoch = 600, Cost = 4.377359867095947, a = -4.795969486236572, b = 80.06636047363281
epoch = 700, Cost = 4.372528553009033, a = -4.798762798309326, b = 80.08812713623047
epoch = 800, Cost = 4.368298053741455, a = -4.801380157470703, b = 80.10850524902344
epoch = 900, Cost = 4.3645734786987305, a = -4.803837299346924, b = 80.12763214111328


In [14]:
def run_gradient_descent(learning_rate, epochs):
    print(f'learning_rate = {learning_rate}')    
    a = torch.tensor(-4.0, requires_grad = True)
    b = torch.tensor(80.0, requires_grad = True)    
    for epoch in range(epochs):
        pred = a * x_tensor + b
        error = y_tensor - pred
        cost = torch.mean(error ** 2)
        
        cost.backward()
        
        with torch.no_grad():
            a -= learning_rate * a.grad
            b -= learning_rate * b.grad
        
        a.grad.zero_()
        b.grad.zero_()
        
        #print(f'cost = {cost}, a = {a}, b = {b}, epoch = {epoch}')
        if cost.item()> 100000:
            print('Cost가 너무 큽니다.')
            print(f'cost = {cost}, a = {a}, b = {b}, epoch = {epoch}')
        
        if (epoch + 1) % 100 == 0:
            print(f'Cost = {cost}, a = {a}, b = {b}, epoch = {epoch}')

In [15]:
run_gradient_descent(0.1, 1000)# learning_rate가 너무 커서 Cost 최저점 못 찾음 → 발산

learning_rate = 0.1
Cost가 너무 큽니다.
cost = 4147874.0, a = 2299.154541015625, b = 375.590087890625, epoch = 3
Cost가 너무 큽니다.
cost = 226199248.0, a = -17018.7421875, b = -2102.64013671875, epoch = 4
Cost가 너무 큽니다.
cost = 12335514624.0, a = 125638.1640625, b = 16198.56640625, epoch = 5
Cost가 너무 큽니다.
cost = 672702988288.0, a = -927840.6875, b = -118950.234375, epoch = 6
Cost가 너무 큽니다.
cost = 36685068894208.0, a = 6851787.5, b = 879083.4375, epoch = 7
Cost가 너무 큽니다.
cost = 2000577244430336.0, a = -50598448.0, b = -6491099.0, epoch = 8
Cost가 너무 큽니다.
cost = 1.090991443452887e+17, a = 373654464.0, b = 47935500.0, epoch = 9
Cost가 너무 큽니다.
cost = 5.949595406605222e+18, a = -2759327232.0, b = -353988832.0, epoch = 10
Cost가 너무 큽니다.
cost = 3.244542353295362e+20, a = 20376811520.0, b = 2614102528.0, epoch = 11
Cost가 너무 큽니다.
cost = 1.769373320881395e+22, a = -150476701696.0, b = -19304370176.0, epoch = 12
Cost가 너무 큽니다.
cost = 9.649072449760166e+23, a = 1111225794560.0, b = 142557052928.0, epoch = 13
Cost가 너

In [16]:
run_gradient_descent(0.000001, 500000)

learning_rate = 1e-06
Cost = 29.57923698425293, a = -4.006471633911133, b = 79.99923706054688, epoch = 99
Cost = 29.161123275756836, a = -4.012890338897705, b = 79.99847412109375, epoch = 199
Cost = 28.749895095825195, a = -4.019256114959717, b = 79.99771118164062, epoch = 299
Cost = 28.34542465209961, a = -4.025568962097168, b = 79.9969482421875, epoch = 399
Cost = 27.947582244873047, a = -4.031829833984375, b = 79.99618530273438, epoch = 499
Cost = 27.556276321411133, a = -4.038038730621338, b = 79.99542236328125, epoch = 599
Cost = 27.17144203186035, a = -4.044196128845215, b = 79.99465942382812, epoch = 699
Cost = 26.792978286743164, a = -4.0503010749816895, b = 79.993896484375, epoch = 799
Cost = 26.420894622802734, a = -4.0563530921936035, b = 79.99313354492188, epoch = 899
Cost = 26.054941177368164, a = -4.062355041503906, b = 79.99237060546875, epoch = 999
Cost = 25.695018768310547, a = -4.068306922912598, b = 79.99160766601562, epoch = 1099
Cost = 25.341022491455078, a = -4.07

In [17]:
run_gradient_descent(0.001, 1000)

learning_rate = 0.001
Cost = 4.413830757141113, a = -4.778733253479004, b = 79.93294525146484, epoch = 99
Cost = 4.404530048370361, a = -4.7827372550964355, b = 79.96316528320312, epoch = 199
Cost = 4.396376609802246, a = -4.786367416381836, b = 79.99146270751953, epoch = 299
Cost = 4.389216423034668, a = -4.789767742156982, b = 80.01799774169922, epoch = 399
Cost = 4.382925987243652, a = -4.79295539855957, b = 80.04286193847656, epoch = 499
Cost = 4.377412796020508, a = -4.795940399169922, b = 80.06613159179688, epoch = 599
Cost = 4.372576713562012, a = -4.798735618591309, b = 80.0879135131836, epoch = 699
Cost = 4.36833381652832, a = -4.801354885101318, b = 80.10830688476562, epoch = 799
Cost = 4.364605903625488, a = -4.803813934326172, b = 80.12744903564453, epoch = 899
Cost = 4.361336708068848, a = -4.806109428405762, b = 80.14537048339844, epoch = 999
