In [7]:
from math import e

In [8]:
1 / ( 1 + e **-(-5) )

0.006692850924284857

In [9]:
1 / ( 1 + e**-(0) )

0.5

In [10]:
from math import log

In [11]:
log(2.71828)

0.999999327347282

In [12]:
#log(0)

In [13]:
import numpy as np
from math import e

In [14]:
X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [15]:
y = np.array([0, 0, 1, 1])

y

array([0, 0, 1, 1])

In [16]:
a = 0.1
b = -17

In [17]:
H = a * X + b

H

array([-1.,  0.,  1.,  2.])

In [18]:
def sigmoid(H):
    return 1 / (1 + e ** (-H))

In [20]:
z = sigmoid(H)

z

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

In [21]:
costs = - (y * np.log(z) + (1 - y) * np.log(1 - z))

costs

array([0.31326169, 0.69314718, 0.31326169, 0.12692801])

In [22]:
np.mean(costs)

np.float64(0.36164964165984087)