In [1]:
import numpy as np

import torch

In [2]:
X = np.array([160, 170, 180, 190])

y = np.array([0, 0, 1, 1])

In [3]:
X_mean = np.mean(X)
X_std = np.std(X)

X_norm = (X - X_mean) / X_std

In [4]:
X_norm_tensor = torch.tensor(X_norm, dtype = torch.float32)

y_tensor = torch.tensor(y, dtype = torch.float32)

In [5]:
X_norm_tensor = X_norm_tensor.reshape([-1, 1])

X_norm_tensor

tensor([[-1.3416],
        [-0.4472],
        [ 0.4472],
        [ 1.3416]])

In [6]:
y_tensor = y_tensor.reshape([-1, 1])

y_tensor

tensor([[0.],
        [0.],
        [1.],
        [1.]])

In [7]:
class PerceptronModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)
        
        
    def forward(self, x):
        H = self.linear(x)
        
        return H

In [8]:
torch.manual_seed(42)

In [9]:
model = PerceptronModel()

In [10]:
model.linear.weight

Parameter containing:
tensor([[0.7645]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.8300], requires_grad=True)

In [12]:
model

PerceptronModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [13]:
with torch.no_grad():
    H_test = model(X_norm_tensor)
    
print(f'H_test = {H_test}')

H_test = tensor([[-0.1957],
        [ 0.4881],
        [ 1.1719],
        [ 1.8557]])


In [14]:
learning_rate = 0.1

In [15]:
epochs = 1000

In [16]:
criterion = torch.nn.BCEWithLogitsLoss()

In [17]:
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [18]:
for epoch in range(epochs):
    optimizer.zero_grad()
    
    H = model(X_norm_tensor)
    
    mean_cost = criterion(H, y_tensor)
    
    mean_cost.backward()
    
    optimizer.step()
    
    if epoch % 100 == 0 or epoch == epochs - 1:
        print(
            f'epoch = {epoch},  '
            f'cost = {mean_cost.item()}, '
            f'weight(a) = {model.linear.weight.item()}, '
            f'bias(b) = {model.linear.bias.item()}'
            )
    
    if epoch < 3:
        print(f'model.linear.weight.grad = {model.linear.weight.grad.item()}, '
              f'model.linear.bias.grad = {model.linear.bias.grad.item()}'
        )

epoch = 0,  cost = 0.49546441435813904, weight(a) = 0.7937799692153931, bias(b) = 0.8125285506248474
model.linear.weight.grad = -0.29241466522216797, model.linear.bias.grad = 0.17479334771633148
model.linear.weight.grad = -0.2861534655094147, model.linear.bias.grad = 0.1699182093143463
model.linear.weight.grad = -0.2800719738006592, model.linear.bias.grad = 0.1651712954044342
epoch = 100,  cost = 0.1786704957485199, weight(a) = 2.2900822162628174, bias(b) = 0.17321154475212097
epoch = 200,  cost = 0.12535728514194489, weight(a) = 3.0022096633911133, bias(b) = 0.06158595159649849
epoch = 300,  cost = 0.0992831364274025, weight(a) = 3.5090017318725586, bias(b) = 0.026837127283215523
epoch = 400,  cost = 0.08290056884288788, weight(a) = 3.9122629165649414, bias(b) = 0.013229331001639366
epoch = 500,  cost = 0.07139823585748672, weight(a) = 4.250606060028076, bias(b) = 0.007115956861525774
epoch = 600,  cost = 0.0627891793847084, weight(a) = 4.5434956550598145, bias(b) = 0.0040910658426582