In [38]:
import numpy as np
import torch

from math import e

In [39]:
X = np.array([160, 170, 180, 190])

y = np.array([0, 0, 1, 1])

In [40]:
X_mean = np.mean(X)

X_mean

np.float64(175.0)

In [41]:
X_std = np.std(X)

X_std

np.float64(11.180339887498949)

In [42]:
X_norm = (X - X_mean) / X_std

X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [43]:
X_norm_tensor = torch.tensor(X_norm, dtype=torch.float32)

X_norm_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [44]:
y_tensor = torch.tensor(y, dtype=torch.float32)

y_tensor

tensor([0., 0., 1., 1.])

In [45]:
a = torch.tensor(0.1, dtype=torch.float32, requires_grad=True)
a

tensor(0.1000, requires_grad=True)

In [46]:
b = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)\
    
b

tensor(0., requires_grad=True)

In [47]:
def sigmoid(H):
    return 1 / (1 + e ** (-H) )

In [48]:
H = a.item() * X_norm + b.item()

H

array([-0.13416408, -0.04472136,  0.04472136,  0.13416408])

In [49]:
z = sigmoid(H)

z

array([0.4665092 , 0.48882152, 0.51117848, 0.5334908 ])

In [50]:
epsilon = 1e-7

z_safe = np.clip(z, epsilon, 1 - epsilon)

z_safe

array([0.4665092 , 0.48882152, 0.51117848, 0.5334908 ])

In [51]:
costs = - ( y * np.log(z_safe) + (1 - y) * np.log(1 - z_safe))

costs

array([0.62831345, 0.67103648, 0.67103648, 0.62831345])

In [52]:
mean_costs = np.mean(costs)

mean_costs

np.float64(0.6496749672265923)

In [53]:
learning_rate = 0.1

epochs = 1000

In [54]:
for epoch in range(epochs):
    H = (a * X_norm_tensor) + b
    z = torch.sigmoid(H)
    
    z_safe = torch.clamp(z, epsilon, 1 - epsilon)
    
    costs = - ( y_tensor * torch.log(z_safe) + (1 - y_tensor) * torch.log( 1- z_safe) )
    mean_cost = torch.mean(costs)
    mean_cost.backward()
    
    grad_a = a.grad.item()
    grad_b = b.grad.item()
    
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        
    a.grad.zero_()
    b.grad.zero_()
    
    if epoch % 100 == 0 or epoch == epochs -1 :
        print(
            f'Epoch {epoch},'
            f'cost {mean_cost.item()},'
            f'grad_a {grad_a},'
            f'grad_b {grad_b},'
            f'a: {a},'
            f'b: {b}'
            )

Epoch 0,cost 0.6496750116348267,grad_a -0.4222477078437805,grad_b 7.450580596923828e-09,a: 0.1422247737646103,b: -7.450580707946131e-10
Epoch 100,cost 0.19822488725185394,grad_a -0.10353483259677887,grad_b 0.0,a: 2.069146156311035,b: 1.257285386913054e-08
Epoch 200,cost 0.13378871977329254,grad_a -0.06304024904966354,grad_b -3.725290298461914e-09,a: 2.860633373260498,b: 2.6449558987451383e-08
Epoch 300,cost 0.1041964441537857,grad_a -0.047122832387685776,grad_b -1.862645149230957e-08,a: 3.4015116691589355,b: 2.7683563885716467e-08
Epoch 400,cost 0.08619248867034912,grad_a -0.038250844925642014,grad_b 1.1175870895385742e-08,a: 3.8243885040283203,b: 3.15252641769348e-08
Epoch 500,cost 0.07378648221492767,grad_a -0.03244045376777649,grad_b -3.6670826375484467e-09,a: 4.175775527954102,b: 3.639725676407579e-08
Epoch 600,cost 0.06461308896541595,grad_a -0.02827340178191662,grad_b 5.587935447692871e-09,a: 4.478099822998047,b: 3.457537900430907e-08
Epoch 700,cost 0.05751201882958412,grad_a -0.