In [1]:
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
import pandas as pd

In [4]:
np.random.seed(42)
tf.random.set_seed(42)

In [5]:
H_example = np.array([[-3.0], [-1.0], [0.0], [1.0], [3.0]])

H_example

array([[-3.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 3.]])

In [6]:
tf.sigmoid(H_example)

<tf.Tensor: shape=(5, 1), dtype=float64, numpy=
array([[0.04742587],
       [0.26894142],
       [0.5       ],
       [0.73105858],
       [0.95257413]])>

In [7]:
model = tf.keras.Sequential([
            tf.keras.Input(shape = (1, )),
            tf.keras.layers.Dense(1)
        ])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [9]:
X = np.array([160, 170, 180, 190], dtype = np.float32).reshape(-1, 1)

In [10]:
y = np.array([0, 0, 1, 1], dtype = np.float32).reshape(-1, 1)

In [11]:
X_mean = X.mean()

X_mean

175.0

In [12]:
X_std = X.std()

X_std

11.18034

In [13]:
X_norm = (X - X_mean) / X_std

X_norm

array([[-1.3416408],
       [-0.4472136],
       [ 0.4472136],
       [ 1.3416408]], dtype=float32)

In [14]:
H_before = model(X_norm)

H_before

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 1.3926371 ],
       [ 0.46421233],
       [-0.46421233],
       [-1.3926371 ]], dtype=float32)>

In [15]:
z_before = tf.sigmoid(H_before)

z_before

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.80101293],
       [0.61401296],
       [0.385987  ],
       [0.1989871 ]], dtype=float32)>

In [16]:
H_before.numpy()[:3]

array([[ 1.3926371 ],
       [ 0.46421233],
       [-0.46421233]], dtype=float32)

In [17]:
z_before.numpy()[:2]

array([[0.80101293],
       [0.61401296]], dtype=float32)

In [18]:
lr = 0.1
ep = 1000

In [19]:
model.compile(
    optimizer = tf.keras.optimizers.SGD(learning_rate = lr) ,
    loss = tf.keras.losses.BinaryCrossentropy(from_logits = True)
)

In [20]:
history = model.fit(
                X_norm,
                y,
                epochs = ep,
                verbose = 1
            )

Epoch 1/1000
1/1 [==============================] - 0s 176ms/step - loss: 1.2832
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2381
Epoch 3/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.1945
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.1525
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.1121
Epoch 6/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0732
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0359
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0001
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.9659
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.9332
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.9019
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.8721
Epoch 13/1000
1/1 [============================

In [21]:
history.history['loss']

[1.283233404159546,
 1.2381068468093872,
 1.1945291757583618,
 1.1525146961212158,
 1.1120704412460327,
 1.0731964111328125,
 1.0358856916427612,
 1.0001240968704224,
 0.9658909440040588,
 0.933159589767456,
 0.9018977880477905,
 0.8720684051513672,
 0.8436299562454224,
 0.8165377378463745,
 0.7907440662384033,
 0.7661992311477661,
 0.7428522109985352,
 0.7206509113311768,
 0.6995433568954468,
 0.6794775724411011,
 0.6604021787643433,
 0.6422669887542725,
 0.6250230073928833,
 0.6086227893829346,
 0.593020498752594,
 0.5781722664833069,
 0.5640361309051514,
 0.5505719780921936,
 0.5377417802810669,
 0.5255094766616821,
 0.513840913772583,
 0.5027037858963013,
 0.492067813873291,
 0.48190420866012573,
 0.4721861481666565,
 0.46288836002349854,
 0.4539870023727417,
 0.44545984268188477,
 0.43728598952293396,
 0.4294458031654358,
 0.4219208359718323,
 0.4146939814090729,
 0.4077489972114563,
 0.40107086300849915,
 0.3946452736854553,
 0.3884589672088623,
 0.38249945640563965,
 0.376755058

In [22]:
list( enumerate(history.history['loss']) )

[(0, 1.283233404159546),
 (1, 1.2381068468093872),
 (2, 1.1945291757583618),
 (3, 1.1525146961212158),
 (4, 1.1120704412460327),
 (5, 1.0731964111328125),
 (6, 1.0358856916427612),
 (7, 1.0001240968704224),
 (8, 0.9658909440040588),
 (9, 0.933159589767456),
 (10, 0.9018977880477905),
 (11, 0.8720684051513672),
 (12, 0.8436299562454224),
 (13, 0.8165377378463745),
 (14, 0.7907440662384033),
 (15, 0.7661992311477661),
 (16, 0.7428522109985352),
 (17, 0.7206509113311768),
 (18, 0.6995433568954468),
 (19, 0.6794775724411011),
 (20, 0.6604021787643433),
 (21, 0.6422669887542725),
 (22, 0.6250230073928833),
 (23, 0.6086227893829346),
 (24, 0.593020498752594),
 (25, 0.5781722664833069),
 (26, 0.5640361309051514),
 (27, 0.5505719780921936),
 (28, 0.5377417802810669),
 (29, 0.5255094766616821),
 (30, 0.513840913772583),
 (31, 0.5027037858963013),
 (32, 0.492067813873291),
 (33, 0.48190420866012573),
 (34, 0.4721861481666565),
 (35, 0.46288836002349854),
 (36, 0.4539870023727417),
 (37, 0.445459

In [23]:
for epoch_index, mean_cost in enumerate(history.history['loss']):
    if epoch_index % 100 == 0 or epoch_index == ep - 1:
        print(f'epoch = {epoch_index}, mean_cost = {mean_cost}')

epoch = 0, mean_cost = 1.283233404159546
epoch = 100, mean_cost = 0.22423838078975677
epoch = 200, mean_cost = 0.14264526963233948
epoch = 300, mean_cost = 0.109012670814991
epoch = 400, mean_cost = 0.08932559192180634
epoch = 500, mean_cost = 0.0760233998298645
epoch = 600, mean_cost = 0.06630397588014603
epoch = 700, mean_cost = 0.05884091928601265
epoch = 800, mean_cost = 0.052908219397068024
epoch = 900, mean_cost = 0.04806896671652794
epoch = 999, mean_cost = 0.044078439474105835


In [24]:
weight, bias = model.layers[-1].get_weights()

In [32]:
weight[0][0]

5.353496

In [29]:
bias[0]

8.076312e-09

In [34]:
H = model(X_norm)

In [35]:
H

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-7.182469 ],
       [-2.3941562],
       [ 2.3941562],
       [ 7.182469 ]], dtype=float32)>

In [36]:
tf.sigmoid(H)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[7.5921282e-04],
       [8.3619401e-02],
       [9.1638052e-01],
       [9.9924076e-01]], dtype=float32)>

In [37]:
input_value = 185

input_norm = (input_value - X_mean) / X_std

input_norm

0.8944271969412381

In [43]:
input_norm_array = np.array([[input_norm]], dtype = np.float32)

input_norm_array

array([[[[0.8944272]]]], dtype=float32)

In [45]:
H_new = model(input_norm_array)

H_new

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[4.7883124]]]], dtype=float32)>

In [48]:
probability = tf.sigmoid(H_new)

probability

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.99174225]]]], dtype=float32)>

In [56]:
'농구 선수 인가봐!!' if probability.numpy().item() >= 0.5 else '아닌가봐!!'

'농구 선수 인가봐!!'