In [1]:
import numpy as np
import torch

In [2]:
X = np.array([160, 170, 180, 190])

y = np.array([  0,   0,   1,   1])

In [ ]:
X_mean = np.mean(X)
X_std = np.std(X)

X_norm = (X - X_mean) / X_std

In [4]:
X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [ ]:
X_norm_tensor = torch.tensor(X_norm, dtype = torch.float32)
y_tensor = torch.tensor(y, dtype = torch.float32)

In [6]:
X_norm_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [7]:
y_tensor

tensor([0., 0., 1., 1.])

In [9]:
X_norm_tensor = X_norm_tensor.reshape(-1, 1) 

X_norm_tensor

tensor([[-1.3416],
        [-0.4472],
        [ 0.4472],
        [ 1.3416]])

In [12]:
y_tensor = y_tensor.reshape(-1, 1)

y_tensor

tensor([[0.],
        [0.],
        [1.],
        [1.]])

In [ ]:
class PerceptronModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)
        
    def forward(self, x):
        H = self.linear(x)
        z = torch.sigmoid(H)
        return z