In [1]:
import numpy as np
from math import e

In [2]:
X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [3]:
y = np.array([0, 0, 1, 1])

y

array([0, 0, 1, 1])

In [4]:
X_mean = np.mean(X)

X_mean

np.float64(175.0)

In [5]:
X_std = np.std(X)

X_std

np.float64(11.180339887498949)

In [6]:
X_norm = (X - X_mean) / X_std

X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [7]:
a = 0.1
b = 0.0

In [8]:
def sigmoid(H):
    return 1 / (1 + e ** (-H))

In [9]:
H_X = (X * a) + b

H_X

array([16., 17., 18., 19.])

In [10]:
Z_X = sigmoid(H_X)

Z_X

array([0.99999989, 0.99999996, 0.99999998, 0.99999999])

In [11]:
a_미분값 = np.mean( (Z_X - y) * X )

a_미분값

np.float64(82.49999278763815)

In [12]:
epochs = 1000
epsilon = 1e-7

In [13]:
epsilon

1e-07

In [14]:
1 - epsilon

0.9999999

In [15]:
learning_rate = 0.1
epochs = 1000

In [16]:
for epoch in range(1000):
    H = (a * X_norm) + b
    print(f'H = {H}')
    z = sigmoid(H)
    print(f'z = {z}')
    
    grad_a = np.mean((z - y) * X_norm )
    print(f'grad_a = {grad_a}')
    
    grad_b = np.mean(z - y)
    print(f'grad_b = {grad_b}')
    
    a = a - (learning_rate * grad_a)
    b = b - (learning_rate * grad_b)
    
    print(f'update a = {a}, update b = {b}')
    
    # z가 epsilon 보다 작으면 log(0) -> -∞ epsilon 리턴 -> 1e-7
    # z가 epsilon 보다 크면 -log(0) -> ∞ 1 - epslion 리턴 -> 0.9999 리턴
    z_safe = np.clip(z, epsilon, 1 - epsilon)
    costs = -(y * np.log(z_safe) + (1 - y) * np.log(1 - z_safe))
    #costs = -(y * np.log(z) + (1 - y) * np.log(1 - z))
    mean_cost = np.mean(costs)
    print(f'mean_cost = {mean_cost}')
    print('='*30)

H = [-0.13416408 -0.04472136  0.04472136  0.13416408]
z = [0.4665092  0.48882152 0.51117848 0.5334908 ]
grad_a = -0.42224770144375845
grad_b = 2.7755575615628914e-17
update a = 0.14222477014437584, update b = -2.7755575615628915e-18
mean_cost = 0.6496749678557904
H = [-0.19081455 -0.06360485  0.06360485  0.19081455]
z = [0.45244058 0.48410415 0.51589585 0.54755942]
grad_a = -0.41175534454951257
grad_b = -2.7755575615628914e-17
update a = 0.1834003045993271, update b = 0.0
mean_cost = 0.6320673287872615
H = [-0.24605733 -0.08201911  0.08201911  0.24605733]
z = [0.43879416 0.47950671 0.52049329 0.56120584]
grad_a = -0.4015730318619577
grad_b = 0.0
update a = 0.22355760778552286, update b = 0.0
mean_cost = 0.6153229046100694
H = [-0.299934 -0.099978  0.099978  0.299934]
z = [0.42557362 0.4750263  0.5249737  0.57442638]
grad_a = -0.39170257011507503
grad_b = 0.0
update a = 0.26272786479703036, update b = 0.0
mean_cost = 0.5993952198102015
H = [-0.35248642 -0.11749547  0.11749547  0.3524864