In [18]:
import numpy as np
import torch
from math import e

In [19]:
X = np.array([160, 170, 180, 190])

y = np.array([0,   0,    1,    1])

In [20]:
X_mean = np.mean(X)

In [21]:
X_std = np.std(X)

In [22]:
X_norm = (X - X_mean) / X_std
X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [23]:
X_norm_tensor = torch.tensor(X_norm, dtype = torch.float32)

X_norm_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [24]:
y_tensor = torch.tensor(y, dtype = torch.float32)

y_tensor

tensor([0., 0., 1., 1.])

In [25]:
a = torch.tensor(0.1, dtype = torch.float32, requires_grad = True)

b = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

In [26]:
a

tensor(0.1000, requires_grad=True)

In [27]:
b

tensor(0., requires_grad=True)

In [28]:
learning_rate = 0.1
epochs = 1000

In [29]:
optimizer = torch.optim.SGD([a, b], lr = learning_rate)

optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [30]:
epsilon = 1e-7

In [31]:
epoches = 1000

for epoch in range(epoches):
    optimizer.zero_grad()
    
    H = (a * X_norm_tensor) + b
    z = torch.sigmoid(H)
    
    z_safe = torch.clamp(z, epsilon, 1 - epsilon)
    
    costs = -((y_tensor * torch.log(z_safe)) + ((1 - y_tensor) * torch.log(1 - z_safe)))
    mean_cost = torch.mean(costs)
    mean_cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 or epoch == epochs - 1:
        print(
            f'epoch = {epoch},  '
            f'Cost  = {mean_cost.item()},   '
            f'a     = {a.item()},   '
            f'b     = {b.item()}'
        )
    if epoch < 3:
        grad_a = a.grad.item()
        grad_b = b.grad.item()
        
        print(f' (확인용) a.grad={grad_a}, b.grad={grad_b}')

epoch = 0,  Cost  = 0.6496750116348267,   a     = 0.1422247737646103,   b     = -7.450580707946131e-10
 (확인용) a.grad=-0.4222477078437805, b.grad=7.450580596923828e-09
 (확인용) a.grad=-0.41175535321235657, b.grad=7.450580596923828e-09
 (확인용) a.grad=-0.4015730321407318, b.grad=1.4901161193847656e-08
epoch = 100,  Cost  = 0.19822488725185394,   a     = 2.069146156311035,   b     = 1.257285386913054e-08
epoch = 200,  Cost  = 0.13378871977329254,   a     = 2.860633373260498,   b     = 2.6449558987451383e-08
epoch = 300,  Cost  = 0.1041964441537857,   a     = 3.4015116691589355,   b     = 2.7683563885716467e-08
epoch = 400,  Cost  = 0.08619248867034912,   a     = 3.8243885040283203,   b     = 3.15252641769348e-08
epoch = 500,  Cost  = 0.07378648221492767,   a     = 4.175775527954102,   b     = 3.639725676407579e-08
epoch = 600,  Cost  = 0.06461308896541595,   a     = 4.478099822998047,   b     = 3.457537900430907e-08
epoch = 700,  Cost  = 0.05751201882958412,   a     = 4.744184494018555,   b  