In [1]:
import numpy as np
import torch

In [2]:
X = np.array([160, 170, 180, 190])

y = np.array([  0,   0,   1,   1])

In [3]:
X_mean = np.mean(X)

X_std = np.std(X)

X_norm = (X - X_mean) / X_std

X_norm

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [4]:
X_norm_tensor = torch.tensor(X_norm, dtype = torch.float32)

X_norm_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [5]:
y_tensor = torch.tensor(y, dtype = torch.float32)

y_tensor

tensor([0., 0., 1., 1.])

In [6]:
X_norm_tensor = X_norm_tensor.reshape(-1, 1)

X_norm_tensor

tensor([[-1.3416],
        [-0.4472],
        [ 0.4472],
        [ 1.3416]])

In [7]:
y_tensor = y_tensor.reshape(-1, 1)

y_tensor

tensor([[0.],
        [0.],
        [1.],
        [1.]])

In [8]:
torch.manual_seed(42)

In [9]:
linear = torch.nn.Linear(1, 1)

In [10]:
linear.weight

Parameter containing:
tensor([[0.7645]], requires_grad=True)

In [11]:
linear.bias

Parameter containing:
tensor([0.8300], requires_grad=True)

In [12]:
criterion = torch.nn.BCELoss()

criterion

BCELoss()

In [13]:
learning_rate = 0.1
epochs = 1000

In [14]:
linear.parameters()

<generator object Module.parameters at 0x0000029A883E92A0>

In [15]:
optimizer = torch.optim.SGD(linear.parameters(), lr = learning_rate)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [16]:
list(linear.parameters())

[Parameter containing:
 tensor([[0.7645]], requires_grad=True),
 Parameter containing:
 tensor([0.8300], requires_grad=True)]

In [ ]:
for epoch in range(epochs):
    optimizer.zero_grad()
    
    H = linear(X_norm_tensor)
    z = torch.sigmoid(H)
    
    mean_cost = criterion(z, y_tensor)
    mean_cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 or epoch == epochs - 1:
        print(f'epoch = {epoch}, cost = {mean_cost}, a = {linear.weight.item()}, b = {linear.bias.item()} ')
    if epoch < 3:
        print(f'linear.weight.grad = {linear.weight.grad}, '
              f'linear.bias.grad = {linear.bias.grad}'
              )

epoch = 0, cost = 0.49546441435813904, a = 0.7937799692153931, b =0.8125285506248474 
linear.weight.grad = tensor([[-0.2924]]), linear.bias.grad = tensor([0.1748])
linear.weight.grad = tensor([[-0.2862]]), linear.bias.grad = tensor([0.1699])
linear.weight.grad = tensor([[-0.2801]]), linear.bias.grad = tensor([0.1652])
epoch = 100, cost = 0.1786704957485199, a = 2.2900822162628174, b =0.17321155965328217 
epoch = 200, cost = 0.1253572702407837, a = 3.0022096633911133, b =0.06158595159649849 
epoch = 300, cost = 0.09928308427333832, a = 3.5090017318725586, b =0.02683713100850582 
epoch = 400, cost = 0.08290064334869385, a = 3.9122629165649414, b =0.01322933379560709 
epoch = 500, cost = 0.07139821350574493, a = 4.250606060028076, b =0.007115961983799934 
epoch = 600, cost = 0.0627891942858696, a = 4.5434956550598145, b =0.004091068636626005 
epoch = 700, cost = 0.05606828257441521, a = 4.802371025085449, b =0.002480151830241084 
epoch = 800, cost = 0.05066009610891342, a = 5.034643650054